services:
 db:
   image: mysql:latest
   container_name: ict_project_db
   ports:
     - 3306:3306
   environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=true
     - MYSQL_DATABASE=testdb
   volumes:
     - ~/docker_vols/db:/var/lib/mysql